-- MySQL Script generated by MySQL Workbench
-- Sat Jun  7 19:09:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cloud
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cloud` ;

-- -----------------------------------------------------
-- Schema cloud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cloud` DEFAULT CHARACTER SET utf8 ;
USE `cloud` ;

-- -----------------------------------------------------
-- Table `cloud`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`administrador` (
  `id` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`estado` (
  `codigo` INT NOT NULL,
  `tipo_estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`tutor` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `calificacion_general` DECIMAL(1,1) NULL,
  `respuesta_preg` VARCHAR(45) NULL,
  `tutorcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`carrera` (
  `codigo` INT NOT NULL,
  `nombre_carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`estudiante` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `respuesta_preg` VARCHAR(45) NOT NULL,
  `cod_carrera` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `cod_carrera_idx` (`cod_carrera` ASC),
  CONSTRAINT `fk_estudiante_cod_carrera`
    FOREIGN KEY (`cod_carrera`)
    REFERENCES `cloud`.`carrera` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`motivo` (
  `codigo` INT NOT NULL,
  `tipo_motivo` VARCHAR(60) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`agendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`agendar` (
  `cod_estudiante` INT NOT NULL,
  `cod_tutor` INT NOT NULL,
  `id` INT NOT NULL auto_increment,
  `calf_tutoria` DECIMAL(1,1) NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_final` TIME NOT NULL,
  `cod_estado` INT NOT NULL,
  `cod_motivo` INT NULL,
  PRIMARY KEY (`cod_estudiante`, `cod_tutor`, `id`),
  UNIQUE (`id`),
  INDEX `cod_estado_idx` (`cod_estado` ASC) ,
  INDEX `cod_tutor_idx` (`cod_tutor` ASC) ,
  INDEX `cod_motivo_idx` (`cod_motivo` ASC) ,
  CONSTRAINT `fk_agendar_cod_estado`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `cloud`.`estado` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendar_cod_tutor`
    FOREIGN KEY (`cod_tutor`)
    REFERENCES `cloud`.`tutor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendar_cod_estudiante`
    FOREIGN KEY (`cod_estudiante`)
    REFERENCES `cloud`.`estudiante` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendar_cod_motivo`
    FOREIGN KEY (`cod_motivo`)
    REFERENCES `cloud`.`motivo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`modificar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`modificar` (
  `cod_admin` INT NOT NULL,
  `cod_agendar` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`cod_admin`, `cod_agendar`),
  INDEX `cod_agendar_idx` (`cod_agendar` ASC) ,
  CONSTRAINT `fk_modificar_cod_admin`
    FOREIGN KEY (`cod_admin`)
    REFERENCES `cloud`.`administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modificar_cod_agendar`
    FOREIGN KEY (`cod_agendar`)
    REFERENCES `cloud`.`agendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`dia` (
  `id` INT NOT NULL,
  `dia` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`horario` (
  `id` INT NOT NULL,
  `id_dia` INT NOT NULL,
  `cod_tutor` INT NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_dia_idx` (`id_dia` ASC) ,
  INDEX `cod_tutor_idx` (`cod_tutor` ASC) ,
  CONSTRAINT `fk_horario_id_dia`
    FOREIGN KEY (`id_dia`)
    REFERENCES `cloud`.`dia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_cod_tutor`
    FOREIGN KEY (`cod_tutor`)
    REFERENCES `cloud`.`tutor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`disponibilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`disponibilidad` (
  `cod_tutor` INT NOT NULL,
  `hora_i` TIME NOT NULL,
  `hora_fn` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `id_horario` INT NOT NULL,
  `cod_estado` INT NOT NULL,
  PRIMARY KEY (`cod_tutor`, `hora_i`, `hora_fn`, `fecha`, `id_horario`),
  INDEX `cod_estado_idx` (`cod_estado` ASC) ,
  INDEX `id_horario_idx` (`id_horario` ASC) ,
  CONSTRAINT `fk_disponibilidad_cod_tutor`
    FOREIGN KEY (`cod_tutor`)
    REFERENCES `cloud`.`tutor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidad_cod_estado`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `cloud`.`estado` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidad_id_horario`
    FOREIGN KEY (`id_horario`)
    REFERENCES `cloud`.`horario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`area` (
  `codigo` INT NOT NULL,
  `nombre_area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`area_tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`area_tutor` (
  `cod_tutor` INT NOT NULL,
  `cod_area` INT NOT NULL,
  PRIMARY KEY (`cod_tutor`, `cod_area`),
  INDEX `cod_area_idx` (`cod_area` ASC) ,
  CONSTRAINT `fk_area_tutor_cod_tutor`
    FOREIGN KEY (`cod_tutor`)
    REFERENCES `cloud`.`tutor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_tutor_cod_area`
    FOREIGN KEY (`cod_area`)
    REFERENCES `cloud`.`area` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`profesor` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`, `nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`area_profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`area_profesor` (
  `cod_profesor` INT NOT NULL,
  `cod_area` INT NOT NULL,
  PRIMARY KEY (`cod_profesor`, `cod_area`),
  INDEX `cod_area_idx` (`cod_area` ASC) ,
  CONSTRAINT `fk_area_profesor_cod_profesor`
    FOREIGN KEY (`cod_profesor`)
    REFERENCES `cloud`.`profesor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_profesor_cod_area`
    FOREIGN KEY (`cod_area`)
    REFERENCES `cloud`.`area` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`tipo` (
  `id` INT NOT NULL,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`materia` (
  `id` INT NOT NULL,
  `nombre_materia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloud`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloud`.`archivo` (
  `id` INT NOT NULL auto_increment,
  `ruta` VARCHAR(200) NOT NULL,
  `cod_profesor` INT NOT NULL,
  `cod_estudiante` INT NOT NULL,
  `cod_estado` INT NOT NULL,
  `id_tipo` INT NOT NULL,
  `id_materia` INT NOT NULL,
  `tamaño` VARCHAR(10) NOT NULL,
  `cod_area` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `cod_profesor_idx` (`cod_profesor` ASC) ,
  INDEX `cod_estado_idx` (`cod_estado` ASC) ,
  INDEX `id_tipo_idx` (`id_tipo` ASC) ,
  INDEX `id_materia_idx` (`id_materia` ASC) ,
  INDEX `cod_estudiante_idx` (`cod_estudiante` ASC) ,
  INDEX `cod_area_idx` (`cod_area` ASC) ,
  CONSTRAINT `fk_archivo_cod_profesor`
    FOREIGN KEY (`cod_profesor`)
    REFERENCES `cloud`.`profesor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_cod_estado`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `cloud`.`estado` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_id_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `cloud`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_id_materia`
    FOREIGN KEY (`id_materia`)
    REFERENCES `cloud`.`materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_cod_estudiante`
    FOREIGN KEY (`cod_estudiante`)
    REFERENCES `cloud`.`estudiante` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_cod_area`
    FOREIGN KEY (`cod_area`)
    REFERENCES `cloud`.`area` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
